name: TwitchLive
version: 1.0.0
author: RyTheFirst
website: rythefirst.uk
main: uk.rythefirst.twitch.Main
api-version: 1.16
commands:
 live:
  description: check if live
 twitch:
  description: check if live